(ns sigmund.test-sigar
  (:use sigmund.sigar
        clojure.pprint))

(pprint (who))
(pprint (uptime))
(pprint (tcp-info))
(pprint (thread-cpu-info))
(pprint (swap-info))
(pprint (resource-limit))
(pprint (proc-time (pid)))
(pprint (proc-state (pid)))
(pprint (proc-stats))
;;(pprint (proc-port tcp 22)) ;; Figure out what to do
(pprint (proc-modules (pid)))
(pprint (proc-memory (pid)))
(pprint (all-procs))
;;(pprint (proc-fd (pid))) ;; Not Implemented
(pprint (proc-exe (pid)))
(pprint (proc-env (pid)))
(pprint (proc-cred-name (pid)))
(pprint (proc-cred (pid)))
(pprint (proc-cpu-info (pid)))
(pprint (nfs-server))
(pprint (nfs-client))
;;(pprint (net-stat (byte-array [(byte 192) (byte 168) (byte 1) (byte 1)]) 80))
(pprint (net-listen-addr 22))
(pprint (all-net-interfaces))
(pprint (all-net-connections 0))
;;(pprint (multi-process-cpu ""))
;;(pprint (multi-process-memory ""))
(pprint (memory))
(pprint (load-avg))
(pprint (fqdn))
(pprint (fs-usage "/app"))
(pprint (mounted-fs-usage "/"))
(pprint (fs-map))
(pprint (all-fs))
(pprint (file-info "/app"))
(pprint (dir-usage "/app"))
(pprint (cpu-percentages))
(pprint (cpu-stats))
(pprint (all-cpu-info))
(pprint (all-cpu-stats))
